language: python
python:
- "2.7" 

before_install:
- "sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable"
- "sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/pcl"
- "sudo apt-get update"
- "pip install -U -q cython"
- "export DEBIAN_FRONTEND=noninteractive"
- "sudo apt-get -qq install libpcl-all python-matplotlib liblas-c2 python-liblas"
- "pip install coverage"
- "pip install -r requirements.txt"
- "sudo ln -s /usr/lib/liblas_c.so.2.2.0 /usr/lib/liblas_c.so"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
