language: python

virtualenv: 
  system_site_packages: true

python:
- "2.7" 

before_install:
# "sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable"
- "export DEBIAN_FRONTEND=noninteractive"
- "sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/pcl"
- "sudo apt-get update"
- "pip install -U cython"
# ATLAS is installed to speed up scikit-learn build (shouldn't build its own)
- "sudo apt-get -qq install libpcl-all python-liblas liblas-bin liblas1 liblas-dev libatlas-base-dev python-gdal"
- "sudo apt-get -qq install python-numpy-dev python-scipy python-matplotlib"
- "pip install coverage"
- "pip install -r requirements.txt"
# python-liblas will try to open  liblas_c.so
- "sudo ln -s /usr/lib/liblas_c.so.2.2.0 /usr/lib/liblas_c.so"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=scripts,patty

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
