language: python
python:
- "2.7" 

before_install:
- "sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/pcl"
- "sudo apt-get -qq update"
- "pip install -U -q cython"
- "export DEBIAN_FRONTEND=noninteractive"
- "sudo apt-get -qq install libpcl-all python-matplotlib"
- "pip install python-coveralls"
- "pip install -r requirements.txt"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script: nosetests

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
