#!/bin/sh
#$ -S /bin/sh
#$ -N patty
#$ -l h_rt=00:15:00
#$ -wd /home/niels/PattyAnalytics/scripts/pmpf
#$ -pe javagat 1

echo "script running"

cat $PE_HOSTFILE

for host in `cat $PE_HOSTFILE | cut -d " " -f 1` ; do
	for i in {0..7}
	do
  		ssh -o StrictHostKeyChecking=false $host "cd `pwd` && ./run-slave"&
	done
done

wait
exit 0
